// Regenerates the comparison in docs/, from this repository's own build.
//
// Two things make this worth having as a script rather than a remembered
// command. It measures `dist/` rather than whatever `impronta` npm happens to
// resolve, so the numbers in the README always describe the code in the tree,
// and it cannot silently drift by a release. And it keeps the comparison in the
// package it is a claim about: the harness publishes the field on its own, and
// the conflict of interest lives here, where the reader expects it.
//
//   npm run report
//
// The subjects are whatever incumbents are installed as devDependencies plus
// the local build, appended last. Nothing about the local build is special to
// the harness: same suites, same probes, same thin adapter shape.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import {
  builtinSubjects,
  collisionChart,
  defineSubject,
  depthChart,
  reportCollisions,
  reportConformance,
  reportCoverage,
  reportDepth,
  reportDeterminism,
  reportHeader,
  runCollisions,
  runConformance,
  runCoverage,
  runDepth,
  runDeterminism,
} from "serializer-conformance";

import { imprint, jcs } from "../dist/index.js";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const docs = join(root, "docs");

const { version } = JSON.parse(
  await import("node:fs/promises").then((fs) => fs.readFile(join(root, "package.json"), "utf8")),
);

// The harness ships adapters that load `impronta` from node_modules. A package
// cannot resolve itself that way, so the local build is registered by hand.
// Same shape as every other adapter: call it the way the README says, record
// what comes back, no normalization and no repair.
const local = [
  defineSubject({
    name: "impronta.imprint",
    kind: "serializer",
    source: `impronta@${version} (this build)`,
    note: "extended mode: the whole JavaScript value graph, type-tagged and length-prefixed",
    run: (value) => imprint(value),
  }),
  defineSubject({
    name: "impronta.jcs",
    kind: "jcs",
    source: `impronta@${version} (this build)`,
    note:
      "strict RFC 8785 mode: refuses what JSON cannot express, and inherits JSON's own " +
      "conflations (a Date and its ISO string are the same JSON document, so they must collide here)",
    run: (value) => jcs(value),
  }),
];

const { subjects: installed, missing } = await builtinSubjects();
// Drop any npm-resolved impronta so a stale installed copy cannot shadow the
// build under test, and keep ours last so the table is not a leaderboard.
const subjects = [...installed.filter((s) => !s.name.startsWith("impronta.")), ...local];

let out = reportHeader(subjects, missing.filter((m) => m !== "impronta"));
out += reportConformance(subjects.filter((s) => s.kind !== "hash").map(runConformance)) + "\n";

const collisions = subjects.map(runCollisions);
out += reportCollisions(collisions) + "\n";
out += reportDeterminism(subjects.map(runDeterminism)) + "\n";
out += reportCoverage(subjects.map(runCoverage)) + "\n";

const depth = subjects.map(runDepth);
out += reportDepth(depth) + "\n";

const preamble = `# impronta, measured against the field

Generated by [serializer-conformance](https://github.com/destbreso/serializer-conformance),
a neutral harness written before this library and which treats it as one more
adapter. That harness publishes its own numbers with impronta *not* installed;
this document is the other half, where the comparison belongs to the package
making the claim.

Regenerate it from a checkout:

\`\`\`bash
npm run report
\`\`\`

It measures \`dist/\`, so these numbers describe the code in this tree rather
than a published release. Every other version measured is in the source column.
Stack limits in the depth suite move between runs and machines; read those as
orders of magnitude.

---

`;

mkdirSync(docs, { recursive: true });
writeFileSync(join(docs, "REPORT.md"), preamble + out, "utf8");
writeFileSync(join(docs, "collisions.svg"), collisionChart(collisions), "utf8");
writeFileSync(join(docs, "depth.svg"), depthChart(depth), "utf8");

const total = collisions.reduce((n, r) => n + r.collisions, 0);
const mine = collisions.filter((r) => r.subject.startsWith("impronta."));
process.stderr.write(
  `wrote docs/REPORT.md, docs/collisions.svg, docs/depth.svg\n` +
    `${subjects.length} subjects, ${total} collisions across the field, ` +
    `${mine.map((r) => `${r.subject}=${r.collisions}`).join(" ")}\n`,
);
